### ISSUE TITLE
Error en el test

### ISSUE THREAD

**Issue by CNB-24-25** [CNB-24-25/practica_dwec_gestor_presupuesto#2]
@pedroprieto no he hecho ninguna modificación ni he usado ningún otro ordenador, he ido alternando, eso sí para practicar, hacer los commit desde consola y desde la interfaz de github en el Visual code, pero siempre desde mi propio ordenador y cuenta.

**Comment by CNB-24-25** [comment]
@pedroprieto no estaba haciendo un pull Request, estaba haciendo "git pull profesor master" para actualizar los posibles cambios, cuando ocurrió lo del código de consola.
Por otro lado, los test, se me siguen quedando congelados en el número 2.

**Comment by pedroprieto** [comment]
Ah, ok... Te habían salido conflictos. Pero puedes dejar tus cambios, tranquilamente. En cualquier caso, no tienes que hacerlo, ya que no hay cambios importantes.

En cuanto a tu error, dos cosas:
- Primero, elimina la carpeta `cypress` de tu repositorio. Además, añade una entrada `cypress` a tu `.gitignore` para no subirla al repositorio si se vuelve a crear. Esa carpeta ocupa más de 60MB, por lo que ralentiza todo mucho.
- En cuanto al test, el problema es que se queda esperando a que aparezca el formulario. Pero tú lo que has hecho es asignar el mismo manejador de evento antiguo, el que utilizaba `prompt`, al botón de `Editar gasto (formulario)`. Por ello, el `prompt` bloquea la página y causa el bloqueo del test, que se queda esperando a que aparezca un formulario que nunca aparecerá. Corrígelo para llamar a un nuevo manejador de evento que muestre el formulario de edición.

Un saludo!

**Comment by CNB-24-25** [comment]
Vale, muchas gracias!! ni me acordaba que había dejado eso ahí para
reescribirlo en un futuro!
Muchas gracias Pedro!
