### ISSUE TITLE
No sé por dónde tirar

### ISSUE THREAD

**Issue by CNB-24-25** [CNB-24-25/practica_dwec_gestor_presupuesto#4]
@pedroprieto.
Buenas tardes Pedro, llevo todo el día peleándome con la función EditarHandleFormulario.
No sé cómo añadirla al formulario, he intentado hacer un eGasto.append (que es el DIV.gasto)
También he probado con el ParentNode del botón editar.
Ya no sé qué más probar... porque si ves mi código, cuando le hago controlesprincipales.append, el formulario sí me funciona, pero si lo saco de ahí no va.

https://github.com/user-attachments/assets/da167f6e-d8af-40dd-82f4-e0bd74b8b56c

**Comment by pedroprieto** [comment]
Buenas,
Aquí tienes un fallo:
https://github.com/CNB-24-25/practica_dwec_gestor_presupuesto/blob/fda6fc93033024a99d67cd63eb6df7ccffc44720/js/gestionPresupuestoWeb.js#L178

Supongo que no es `botonAnyadirGasto`, sino `botonEditarGasto`...

**Comment by CNB-24-25** [comment]
Eso lo modifiqué después del último Commit, pero sigo sin saber cómo solventar el problema que te he comentado

**Comment by pedroprieto** [comment]
El formulario de edición no tiene que ir en controles principales, sino dentro del propio gasto:
https://github.com/CNB-24-25/practica_dwec_gestor_presupuesto/blob/fda6fc93033024a99d67cd63eb6df7ccffc44720/js/gestionPresupuestoWeb.js#L175
Puedes probar algo como esto, para que aparezca donde debe:
```js
event.currentTarget.parentElement.append(formulario);
```
Por otro lado, yo no tengo la misma funcionalidad que tú. ¿Has subido todos los cambios? Por ejemplo, al pulsar en el botón de envío se recarga la página...

No sé si lo habrás solucionado, pero aquí:
https://github.com/CNB-24-25/practica_dwec_gestor_presupuesto/blob/fda6fc93033024a99d67cd63eb6df7ccffc44720/js/gestionPresupuestoWeb.js#L180
estás utilizando una **función** manejadora de eventos, en lugar de un **objeto** manejador de eventos, tal como hiciste en la primera funcionalidad de edición:
https://github.com/CNB-24-25/practica_dwec_gestor_presupuesto/blob/fda6fc93033024a99d67cd63eb6df7ccffc44720/js/gestionPresupuestoWeb.js#L132-L134
https://github.com/CNB-24-25/practica_dwec_gestor_presupuesto/blob/fda6fc93033024a99d67cd63eb6df7ccffc44720/js/gestionPresupuestoWeb.js#L47

Con el formulario tienes que hacer algo parecido.

**Comment by CNB-24-25** [comment]
Buenos días Pedro, primeramente gracias por contestar un sábado, fuera de tu horario laboral.
Al final he encontrado el fallo: tenía repintar en ambas funciones y por algún motivo que no alcanzo a entender me daba fallos. Además he usado parentNode para el botón y el formulario y, a falta de pasar los test, por lo pronto ya tengo el formulario en su sitio.
Gracias
